---
  - name: Postgres Version
    hosts: postgres
    become: yes
    become_user: root
    tasks:
      - name: Checking Postgres version
        yum:
          name: postgresql12-server.x86_64
          state: latest
      - name: Ensure postgres is running
        service:
          name: postgresql-12
          state: started
      - name: Zabbix agent is running
        service:
          name: zabbix-agent
          state: started   
          
